# Generated by Django 3.1.2 on 2020-11-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('id_number', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('school', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('validated', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('investment_date', models.DateTimeField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loanrequest')),
            ],
        ),
    ]
