# Generated by Django 3.1.2 on 2021-01-08 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "short_bio",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "profile_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/photos",
                    ),
                ),
                ("id_number", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("school", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=8
                    ),
                ),
                ("description", models.CharField(max_length=5000)),
                ("status", models.IntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("investment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.loanrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IDVerifications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "person_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("validated", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
