# Generated by Django 3.1.2 on 2021-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="requested_value_atto_dai",
            field=models.CharField(max_length=40),
        ),
    ]
