# Generated by Django 3.1.2 on 2020-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='validated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
