# Generated by Django 3.1.2 on 2020-11-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201128_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
