# Generated by Django 3.1.2 on 2021-01-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210112_1928"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="loan_identifier",
            new_name="identifier",
        ),
    ]
